# NUMPY(use # to create a heading)

In [1]:
# This is a cell

# import numpy 
import numpy as np

In [2]:
# Array in numpy
lst = [1,2,3]

# a list of python is converted into numpy array
myarr = np.array(lst)

In [3]:
myarr

array([1, 2, 3])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
# creating a array of a particular bit size e.g 32 bit integer
myarr = np.array([1,127,3], np.int8)

In [6]:
myarr

array([  1, 127,   3], dtype=int8)

In [7]:
# Accessing the elements
myarr[0]

1

In [8]:
# for 2d array
myarr = np.array([[1,2,3]], np.int32)

In [9]:
myarr

array([[1, 2, 3]])

In [10]:
# Accessing elements of 2D array
myarr[0]

array([1, 2, 3])

In [11]:
# 1st array from 2D array -> got 1D array
# 1st element from 1D array
myarr[0, 1]

2

In [12]:
# changing the value of the cell
myarr[0, 1] = 100

In [13]:
# get the structure of the array
myarr.shape

(1, 3)

In [14]:
# get the dtype
myarr.dtype

dtype('int32')

In [15]:
# 1) Conversion from other python structures(list, tuples, dict, strings)

In [16]:
# List
listArray = np.array([[1,2,3], [ 23,43,54], [98,48,62]])

In [17]:
listArray

array([[ 1,  2,  3],
       [23, 43, 54],
       [98, 48, 62]])

In [18]:
listArray.size

9

In [19]:
listArray.shape

(3, 3)

In [20]:
listArray.dtype

dtype('int32')

In [21]:
listArray[1, 2] = 500

In [22]:
listArray

array([[  1,   2,   3],
       [ 23,  43, 500],
       [ 98,  48,  62]])

In [23]:
# Dict
dictArray = np.array({12,23,34})

In [24]:
# not recommended
dictArray

array({34, 12, 23}, dtype=object)

In [25]:
# 2) Intrinsic numpy array creation -> functions to create array

In [26]:
# zeros 

# only 1 row  &2 column i.e a 1D array of zeros
zeros = np.zeros(2)

In [27]:
zeros

array([0., 0.])

In [28]:
zeros.dtype

dtype('float64')

In [29]:
zeros.shape

(2,)

In [30]:
zeros.size

2

In [31]:
# 2D zeros

# 2 rows & 5 columns
zeros = np.zeros((2,5))

In [32]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.dtype

dtype('float64')

In [34]:
zeros.shape

(2, 5)

In [35]:
zeros.size

10

In [36]:
# ones
ones = np.ones(3)

In [37]:
ones

array([1., 1., 1.])

In [38]:
# 2D ones

# 2 rows & 5 columns
ones = np.ones((2,5))

In [39]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
ones.dtype

dtype('float64')

In [41]:
ones.shape

(2, 5)

In [42]:
ones.size

10

In [43]:
ones[0, 1]=2.3

In [44]:
ones

array([[1. , 2.3, 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. ]])

In [45]:
# arange -> just like range function in python 
# creates an array with 0 to (n-1) range

rng = np.arange(10)

In [46]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
lspace = np.linspace(1,50,10)

In [48]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [49]:
# empty array

# creates an empty array of the given size filled with random values
# provide args as tuple if > 1 
emp = np.empty((2,2))

In [50]:
emp

array([[2.12199579e-314, 1.18831764e-311],
       [6.67976753e-321, 6.95250701e-310]])

In [51]:
# empty like array 
# uses previously created array's size to create an empty array

emp_like = np.empty_like(lspace)

In [52]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [53]:
# identity matrix

# creates an identity matrix of size n x n
ide = np.identity(2)

In [54]:
ide

array([[1., 0.],
       [0., 1.]])

In [55]:
ide.shape

(2, 2)

In [56]:
# reshaping the array created from arange

arr = np.arange(99)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [58]:
# use reshape array function of numpy
type(np.reshape)


numpy._ArrayFunctionDispatcher

In [59]:
# Note: 3, 33 gives 99, so the numbers should be equal to n when multiplied back else will not reshape any array

arr.reshape(3,33) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

# Numpy Axis

In [60]:
# 1D array -> one & only axis i.e axis 0 (row in this case)
# 2D array -> 2 axis i.e axis 0(collection of rows) and axis 1 (collection of columns) 

a = [1,2,3]
arr = np.array(a)

In [61]:
arr

array([1, 2, 3])

In [62]:
# to get sum of the axis 0 
arr.sum(axis=0)

6

In [63]:
arr.T

array([1, 2, 3])

In [64]:
# 2D array
a = [[1,2,3], [4,5,6], [7,8,9]] 
arr = np.array(a)

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
# Attributes
# sum of each column (1,4,7 ... ) 

sum = arr.sum(axis=0)
sum

array([12, 15, 18])

In [67]:
# sum of each row ( 1,2,3 ... ) 
sum=arr.sum(axis=1)
sum

array([ 6, 15, 24])

In [68]:
# Transpose the array
at = arr.T
at

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [69]:
# size of the array
arr.size

9

In [70]:
# dimension of the array
arr.ndim

2

In [71]:
# flatten 2D array -> 1D array coversion
af= arr.flat
af

In [72]:
for ele in af:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 

In [73]:
# get the size consumed by an array
s = arr.nbytes
s

36

In [74]:
# Methods args

# for 1D array
arr = np.array([1,3,2,4])
arr

array([1, 3, 2, 4])

In [75]:
# returns the index of max element in the array
arr.argmax()

3

In [76]:
# returns the index of min element in the array
arr.argmin()

0

In [77]:
# returns the array of sorted index when the elements are in sorted order
arr.argsort()

array([0, 2, 1, 3], dtype=int64)

In [78]:
# for 2D array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# max & min index after flattening to 1D array
arr.argmax()

8

In [80]:
arr.argmin()

0

In [81]:
# max of each column (axis 0) 
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [82]:
# min
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [83]:
# max of each row(axis=1)
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [84]:
# min of every row
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [85]:
# sorted form of 2D array
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [86]:
# sorted form of each column
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [87]:
# sorted form of each row
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

# Matrix operations

In [88]:
a1 = np.array([[1,2,3], [2,1,3], [4,2,4]])
a2 = np.array([[2,4,4], [3,1,2], [1,2,3]])
a1

array([[1, 2, 3],
       [2, 1, 3],
       [4, 2, 4]])

In [89]:
a2

array([[2, 4, 4],
       [3, 1, 2],
       [1, 2, 3]])

In [90]:
# addition of two matrices
a1 + a2

array([[3, 6, 7],
       [5, 2, 5],
       [5, 4, 7]])

In [91]:
# subtraction
a1 - a2

array([[-1, -2, -1],
       [-1,  0,  1],
       [ 3,  0,  1]])

In [92]:
# multiplication
a1 * a2

array([[ 2,  8, 12],
       [ 6,  1,  6],
       [ 4,  4, 12]])

In [93]:
# division
a1 / a2

array([[0.5       , 0.5       , 0.75      ],
       [0.66666667, 1.        , 1.5       ],
       [4.        , 1.        , 1.33333333]])

In [94]:
# modulus
a1 % a2

array([[1, 2, 3],
       [2, 0, 1],
       [0, 0, 1]])

In [95]:
# power
a1 ** a2

array([[ 1, 16, 81],
       [ 8,  1,  9],
       [ 4,  4, 64]])

In [96]:
# operators 
a1 > a2

array([[False, False, False],
       [False, False,  True],
       [ True, False,  True]])

In [97]:
# bitwise operations
a1 & a2

array([[0, 0, 0],
       [2, 1, 2],
       [0, 2, 0]])

In [98]:
a1 | a2

array([[3, 6, 7],
       [3, 1, 3],
       [5, 2, 7]])

In [99]:
a1 ^ a2

array([[3, 6, 7],
       [1, 0, 1],
       [5, 0, 7]])

In [103]:
~a1

array([[-2, -3, -4],
       [-3, -2, -4],
       [-5, -3, -5]])

In [101]:
# max element from the matrix
a1.max()

4

In [104]:
# min element from the matrix
a1.min()

1

In [105]:
# sum of all elements
a1.sum()

22

In [108]:
a1

array([[1, 2, 3],
       [2, 1, 3],
       [4, 2, 4]])

In [111]:
# Where method

# returns a tuple of indices for every axis i.e tuple of rows & columns
np.where(a1 > 2) 

(array([0, 1, 2, 2], dtype=int64), array([2, 2, 0, 2], dtype=int64))

In [114]:
# count_nonzero: returns a count of non zero elements in the array
np.count_nonzero(a1)

9

In [116]:
# nonzero: returns tuple of every axis of indices of non zero element
np.nonzero(a1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [119]:
# removes 0,1 from above tuple 
a1[0,1]=0

In [120]:

np.nonzero(a1)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

# Proof that numpy takes less space

In [121]:
import sys

In [122]:
a1 = [1,2,3]

In [123]:
arr = np.array(a1)

In [124]:
# get the size of item of length
sys.getsizeof(1) * len(a1)

84

In [125]:
arr.itemsize * arr.size

12